- name: install mongo
  ansible.builtin.package:
    name: mongodb-org
    state: present

- name: copying mongodb repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: start and enable mongodb
  ansible.builtin.service:
    state: started
    enabled: yes

- name: changing the configuration
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: 127.0.0.1
    replace: 0.0.0.0

- name: restartin mongodb
  ansible.builtin.service:
    state: restarted

