- name: install maven
  ansible.builtin.import_role:
    name: common
    tasks_from: maven

- name: systemd
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd

- name: copy
  ansible.builtin.import_role:
    name: common
    tasks_from: copy

- name: mysql
  ansible.builtin.import_role:
    name: common
    tasks_from: mysql



